spring.application.name=backend-sistemasalgados

spring.datasource.url=jdbc:postgresql://localhost:5432/sistemasalgadosdb
spring.datasource.username=salgados
spring.datasource.password=salgados123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=0l1vi4Fil1p407112o2474bbykittys2
jwt.expiration=86400000